name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install dependencies
        run: |
          gem install nokogiri
          gem install open-uri
      - name: Scrape Twipla
        run: |
          ruby scrape_twipla.rb
      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: twipla-json
          path: json-ld/*.json

  build:
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: twipla-json
          path: json-ld
      - name: Install dependencies
        run: |
          gem install nokogiri
          gem install open-uri
      - name: Convert JSON to Markdown
        run: |
          ruby json_to_md.rb
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Ensure gh-pages branch exists
        run: |
          if ! git show-ref --quiet refs/heads/gh-pages; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github@users.noreply.github.com'
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
            git checkout -
          fi
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github@users.noreply.github.com'
          git add .
          git commit -m 'Deploy to GitHub Pages'
          git push origin `HEAD:refs/heads/gh-pages`

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4